title: "Yidi Wang"
author: "Yidi Wang"
description: "University of Pennsylvania"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: ""}
  #- {file: "about.html", title: "About"}
  - {file: "research.md", title: "Research"}
  - {file: "teaching.md", title: "Teaching"}
  - {url: "CV_website.pdf", title: "CV"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "yidiwang@sas.upenn.edu"}
  - {title: Github, icon: github, url: "https://github.com/ywang-math/"}
  - {title: Subscribe, icon: rss, url: ""}
  #- {title: Constrast Jekyll theme by Niklas Buschmann, url: "https://github.com/niklasbuschmann"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
